name: Greetings for PRs and Issues

on:
  pull_request_target:
  issues:

jobs:
  build:
    name: Welcome New Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |-
            Welcome @${{ github.actor }} :wave:

            It looks like this is your first issue on the KQL-Elasticsearch-Data-Filtering repository!

            If you're reporting an issue related to `false positives` or 'rule ideas,' feel free to share it here.

            Thanks for taking the time to open this issue, and welcome to the KQL-Elasticsearch-Data-Filtering community! :smiley:

          pr-message: |-
            Welcome @${{ github.actor }} :wave:

            It looks like this is your first pull request on the KQL-Elasticsearch-Data-Filtering repository!

            Please make sure your contribution adheres to best practices and has all the necessary elements in place for a successful approval.

            Thanks again, and welcome to the KQL-Elasticsearch-Data-Filtering community! :smiley:
